# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_auto_20160927_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinates',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
