# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0003_coordinates_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinates',
            name='published_date',
        ),
    ]
